package pl.nubet.studymood.domain.usecase

import pl.nubet.studymood.data.repository.LexiconRepository
import pl.nubet.studymood.domain.model.Emotion

class EnsureLexiconSeeded(private val lexiconRepository: LexiconRepository) {
    suspend operator fun invoke() {
        val currentCount = lexiconRepository.count()
        if (currentCount >= 150) return

        if (currentCount > 0) {
            lexiconRepository.deleteAll()
        }

        lexiconRepository.insertAll(generateSeedEmotions())
    }
}

private data class Seed(
    val key: String,
    val pleasant: Int,
    val energy: Int,
    val quadrant: Int,
    val description: String? = null,
)

private fun capWords(input: String): String =
    input
        .split(' ', '-', '_')
        .filter { it.isNotBlank() }
        .joinToString(" ") { part ->
            part.replaceFirstChar { if (it.isLowerCase()) it.titlecase() else it.toString() }
        }

private fun generateSeedEmotions(): List<Emotion> {
    val seeds =
        listOf(
            Seed("ecstatic", 95, 95, 1, "Feeling extremely happy and excited beyond measure."),
            Seed("elated", 90, 90, 1, "Very happy and proud; in high spirits."),
            Seed("thrilled", 88, 85, 1, "Extremely pleased and excited about something."),
            Seed("excited", 85, 85, 1, "Feeling enthusiastic and eager about upcoming events."),
            Seed("joyful", 85, 80, 1, "Full of happiness and delight."),
            Seed("proud", 80, 75, 1, "Feeling deep satisfaction from your achievements."),
            Seed("motivated", 75, 75, 1, "Having a strong reason or desire to do something."),
            Seed("inspired", 75, 70, 1, "Feeling creative and full of new ideas."),
            Seed("playful", 78, 68, 1, "Light-hearted and full of fun; not serious."),
            Seed("amused", 80, 65, 1, "Finding something funny or entertaining."),
            Seed("hopeful", 75, 60, 1, "Feeling optimistic that good things will happen."),
            Seed("cheerful", 85, 60, 1, "Noticeably happy and positive in mood."),
            Seed("lively", 70, 70, 1, "Full of life and energy; animated."),
            Seed("energetic", 70, 80, 1, "Full of energy and enthusiasm."),
            Seed("confident", 70, 65, 1, "Feeling sure about yourself and your abilities."),
            Seed("curious", 65, 70, 1, "Eager to learn or know something."),
            Seed("enthusiastic", 80, 75, 1, "Showing intense interest and excitement."),
            Seed("radiant", 85, 70, 1, "Glowing with joy, health, or confidence."),
            Seed("vibrant", 80, 80, 1, "Full of energy and life; dynamic."),
            Seed("optimistic", 75, 65, 1, "Hopeful and positive about the future."),
            Seed("productive", 75, 75, 1, "Getting a lot done; efficient and effective."),
            Seed("accomplished", 85, 70, 1, "Successfully completed something; skilled."),
            Seed("alive", 80, 70, 1, "Feeling vibrant, energized, and fully present."),
            Seed("amazed", 80, 75, 1, "Filled with wonder and surprise."),
            Seed("awe", 80, 65, 1, "Feeling of reverence mixed with wonder or fear."),
            Seed("challenged", 65, 75, 1, "Stimulated by demanding tasks or situations."),
            Seed("delighted", 85, 70, 1, "Feeling great pleasure and satisfaction."),
            Seed("determined", 75, 80, 1, "Having a firm decision to achieve a goal."),
            Seed("eager", 70, 75, 1, "Excited and impatient to do something."),
            Seed("empowered", 80, 70, 1, "Feeling strong, confident, and in control."),
            Seed("engaged", 70, 70, 1, "Fully involved and interested in something."),
            Seed("focused", 65, 80, 1, "Concentrating fully on a task or goal."),
            Seed("happy", 90, 70, 1, "Feeling pleasure and contentment."),
            Seed("pleasant", 80, 60, 1, "Giving a sense of happy satisfaction."),
            Seed("pleased", 80, 60, 1, "Satisfied and content with something."),
            Seed("surprised", 70, 75, 1, "Feeling mild astonishment from the unexpected."),
            Seed("upbeat", 80, 65, 1, "Cheerful and optimistic in attitude."),
            Seed("wishful", 65, 60, 1, "Desiring something that may not happen."),
            Seed("enraged", 5, 98, 2, "Feeling extremely angry and out of control."),
            Seed("furious", 5, 90, 2, "Extremely angry; in a state of rage."),
            Seed("panicked", 5, 95, 2, "Feeling sudden overwhelming fear and anxiety."),
            Seed("terrified", 10, 90, 2, "Extremely frightened or scared."),
            Seed("anxious", 20, 85, 2, "Worried and nervous about something uncertain."),
            Seed("stressed", 25, 80, 2, "Feeling mental or emotional pressure and tension."),
            Seed("overwhelmed", 20, 85, 2, "Having too much to deal with; feeling buried."),
            Seed("frustrated", 25, 75, 2, "Annoyed because you cannot achieve something."),
            Seed("angry", 20, 80, 2, "Feeling strong displeasure or hostility."),
            Seed("nervous", 35, 75, 2, "Worried or slightly afraid about something."),
            Seed("pressured", 30, 75, 2, "Feeling forced to do something; under stress."),
            Seed("irritated", 35, 70, 2, "Annoyed or slightly angry about something."),
            Seed("restless", 40, 70, 2, "Unable to rest or relax; constantly moving."),
            Seed("uneasy", 35, 65, 2, "Slightly anxious or uncomfortable about something."),
            Seed("worried", 35, 70, 2, "Anxious or troubled about actual or potential problems."),
            Seed("agitated", 30, 80, 2, "Feeling troubled or nervous; unable to relax."),
            Seed("tense", 30, 65, 2, "Feeling nervous and unable to relax."),
            Seed("alarmed", 20, 85, 2, "Suddenly frightened or disturbed by something."),
            Seed("shocked", 20, 75, 2, "Surprised and upset by something unexpected."),
            Seed("apprehensive", 30, 70, 2, "Anxious that something bad might happen."),
            Seed("frightened", 15, 85, 2, "Feeling afraid or scared of something."),
            Seed("annoyed", 35, 65, 2, "Slightly angry; irritated by something."),
            Seed("confused", 30, 60, 2, "Unable to think clearly; uncertain."),
            Seed("embarrassed", 25, 65, 2, "Feeling ashamed or awkward in front of others."),
            Seed("envious", 25, 70, 2, "Wanting what someone else has; jealous."),
            Seed("fomo", 25, 80, 2, "Fear of missing out on experiences others are having."),
            Seed("impassioned", 40, 85, 2, "Filled with intense feeling or enthusiasm."),
            Seed("irate", 15, 85, 2, "Very angry; furious."),
            Seed("jealous", 20, 75, 2, "Envious of someone's advantages or possessions."),
            Seed("jittery", 35, 80, 2, "Nervous and unable to stay still."),
            Seed("livid", 10, 90, 2, "Extremely angry; furiously mad."),
            Seed("peeved", 40, 60, 2, "Annoyed or irritated by something minor."),
            Seed("repulsed", 10, 65, 2, "Feeling intense disgust or aversion."),
            Seed("scared", 15, 80, 2, "Feeling fear or worry about danger or pain."),
            Seed("troubled", 30, 65, 2, "Worried or disturbed about a problem."),
            Seed("depressed", 5, 10, 3, "Feeling very sad and without hope or energy."),
            Seed("hopeless", 10, 15, 3, "Feeling that there is no chance things will improve."),
            Seed("lonely", 15, 20, 3, "Feeling sad from being alone or disconnected."),
            Seed("sad", 20, 20, 3, "Feeling unhappy or sorrowful."),
            Seed("discouraged", 25, 25, 3, "Having lost confidence or enthusiasm."),
            Seed("disappointed", 25, 30, 3, "Sad because expectations were not met."),
            Seed("helpless", 15, 25, 3, "Unable to help yourself or control a situation."),
            Seed("fatigued", 25, 15, 3, "Extremely tired mentally or physically."),
            Seed("bored", 35, 20, 3, "Feeling weary from lack of interest or activity."),
            Seed("drained", 20, 15, 3, "Completely exhausted of energy or resources."),
            Seed("melancholic", 20, 25, 3, "Feeling a deep, pensive sadness."),
            Seed("resigned", 30, 20, 3, "Accepting something unpleasant with no hope of change."),
            Seed("ashamed", 10, 30, 3, "Feeling embarrassed or guilty about something."),
            Seed("guilty", 10, 35, 3, "Feeling responsible for wrongdoing."),
            Seed("empty", 20, 15, 3, "Feeling hollow or lacking purpose and meaning."),
            Seed("numb", 25, 10, 3, "Unable to feel emotions; emotionally detached."),
            Seed("insecure", 25, 40, 3, "Lacking confidence about yourself or relationships."),
            Seed("alienated", 20, 25, 3, "Feeling isolated or estranged from others."),
            Seed("apathetic", 30, 10, 3, "Showing no interest or concern about anything."),
            Seed("burned out", 15, 10, 3, "Exhausted from prolonged stress or overwork."),
            Seed("despair", 10, 10, 3, "Complete loss of hope; utter hopelessness."),
            Seed("disconnected", 25, 20, 3, "Feeling separated or detached from others."),
            Seed("disengaged", 30, 25, 3, "Not involved or interested in something."),
            Seed("disgusted", 15, 35, 3, "Feeling revulsion or strong disapproval."),
            Seed("disheartened", 20, 20, 3, "Having lost determination or confidence."),
            Seed("down", 25, 20, 3, "Feeling unhappy or in low spirits."),
            Seed("excluded", 15, 25, 3, "Feeling left out or rejected by others."),
            Seed("exhausted", 15, 10, 3, "Completely drained of physical or mental energy."),
            Seed("forlorn", 10, 15, 3, "Sad and lonely; abandoned."),
            Seed("glum", 25, 20, 3, "Looking or feeling sad and gloomy."),
            Seed("humiliated", 5, 30, 3, "Deeply embarrassed or ashamed in public."),
            Seed("lost", 20, 25, 3, "Feeling confused about direction or purpose."),
            Seed("meh", 35, 20, 3, "Indifferent; neither good nor bad."),
            Seed("miserable", 10, 15, 3, "Very unhappy or uncomfortable."),
            Seed("nostalgic", 40, 25, 3, "Longing for the past; sentimental yearning."),
            Seed("pessimistic", 20, 30, 3, "Expecting the worst; negative about the future."),
            Seed("tired", 25, 15, 3, "Needing rest or sleep; weary."),
            Seed("trapped", 15, 30, 3, "Feeling unable to escape a situation."),
            Seed("vulnerable", 25, 30, 3, "Exposed to possible harm or emotional hurt."),
            Seed("peaceful", 85, 20, 4, "Feeling calm and free from worries or disturbances."),
            Seed("calm", 80, 25, 4, "Not showing or feeling nervousness or strong emotion."),
            Seed("relaxed", 80, 25, 4, "Free from tension and anxiety; at ease."),
            Seed("settled", 80, 30, 4, "Comfortable and stable; at peace."),
            Seed("satisfied", 75, 35, 4, "Content with what you have or achieved."),
            Seed("serene", 85, 25, 4, "Calm, peaceful, and untroubled."),
            Seed("cozy", 80, 25, 4, "Feeling warm, comfortable, and secure."),
            Seed("safe", 70, 30, 4, "Protected from danger or harm; secure."),
            Seed("grateful", 75, 30, 4, "Feeling thankful and appreciative."),
            Seed("comfortable", 80, 30, 4, "Feeling physically and mentally at ease."),
            Seed("relieved", 70, 30, 4, "No longer feeling worried or anxious."),
            Seed("unworried", 70, 35, 4, "Free from anxiety or concern."),
            Seed("easygoing", 65, 35, 4, "Relaxed and tolerant in approach."),
            Seed("meditative", 75, 15, 4, "Deeply thoughtful and contemplative."),
            Seed("tranquil", 85, 15, 4, "Free from disturbance; perfectly calm."),
            Seed("reflective", 70, 25, 4, "Thinking deeply or carefully about something."),
            Seed("rested", 70, 20, 4, "Refreshed and recovered from tiredness."),
            Seed("appreciative", 75, 30, 4, "Recognizing and valuing the good things."),
            Seed("fulfilled", 80, 35, 4, "Satisfied with life and what you've achieved."),
            Seed("accepted", 75, 35, 4, "Feeling welcomed and understood by others."),
            Seed("sympathetic", 65, 30, 4, "Feeling compassion for someone's troubles."),
            Seed("understood", 75, 35, 4, "Feeling that others comprehend your feelings."),
            Seed("balanced", 70, 40, 4, "In a state of emotional and mental equilibrium."),
            Seed("blessed", 85, 30, 4, "Feeling fortunate and favored."),
            Seed("blissful", 90, 35, 4, "Experiencing perfect happiness and joy."),
            Seed("carefree", 80, 40, 4, "Free from anxiety or responsibility."),
            Seed("chill", 75, 25, 4, "Relaxed and easygoing."),
            Seed("compassionate", 70, 30, 4, "Feeling sympathy and concern for others."),
            Seed("connected", 70, 35, 4, "Feeling close and bonded with others."),
            Seed("content", 75, 30, 4, "Satisfied and at peace with your situation."),
            Seed("empathetic", 65, 30, 4, "Understanding and sharing others' feelings."),
            Seed("good", 70, 40, 4, "Feeling generally positive and well."),
            Seed("included", 70, 35, 4, "Feeling part of a group; welcomed."),
            Seed("loved", 85, 40, 4, "Feeling cared for and cherished by others."),
            Seed("moved", 70, 35, 4, "Emotionally touched or affected."),
            Seed("respected", 75, 35, 4, "Feeling valued and admired by others."),
            Seed("secure", 75, 30, 4, "Confident and free from fear or doubt."),
            Seed("supported", 70, 30, 4, "Feeling backed up and helped by others."),
            Seed("thankful", 75, 30, 4, "Expressing gratitude for what you have."),
            Seed("valued", 75, 35, 4, "Feeling appreciated and important to others."),
            Seed("neutral", 50, 50, 0, "Not strongly pleasant or unpleasant; balanced state."),
        )

    return seeds.map { seed ->
        Emotion(
            id = seed.key,
            label = capWords(seed.key),
            synonym = null,
            description = seed.description,
            pleasantDefault = seed.pleasant,
            energyDefault = seed.energy,
            quadrant = seed.quadrant,
            custom = false,
        )
    }
}
